/*
 * noirelight extra commands
 * AGPL-3-or-later

*/

exports.noirelight2_command = {
	SAPI: 0.2,
	mname: "streamthumb",
	mdesc: "Returns an URL to a thumbnail of a stream (by name)",
	cmdname: "streamthumb",
	pipeable: 0,
	clearance: 0,
	errmsg: "cannot run command nam",
	nlt2_compatible: true,
	cooldowns: {
				global: 0,
				channel: 5,
				user: 10
				},
	minternal: 0,
	mgreenlist: 0,
	numeric_data: null,
	text_data: null,
	extra_modules: null,
	aliases: ["st"]
}

exports.nlt2_cmd_help = {
	shorthelp: "Usage: st <channel name> <optional resolution>. Returns a link to an automatically generated thumbnail of a Twitch channel. Default height is 248px, you may specify other values as the 2nd parameter (160p, 360p, 480p, 720p or 1080p)",
	exthelp: "Usage: st <channel name> <optional resolution>. Returns a link to an automatically generated thumbnail of a Twitch channel. Default height is 248px, you may specify other values as the 2nd parameter (160p, 360p, 480p, 720p or 1080p). These thumbnails are automatically generated by Twitch, they are regularly updated during the broadcast. Thumbnail and resolution availability is not guaranteed. The returned value is a generated string, the bot doesn't check its availability"
}

